env: "local" # local, dev, prod

# postgres config
postgress:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "132415"
  dbname: "url-shortener"

# server config
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение запроса и такое же время на отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
